### PR TITLE
Add automatic hook based on an environment variable

### LINKED ISSUE #24: Add production switch
A few people now have pointed out it'd be neat to have a production switch.

While I personally would remove the `import` statement manually and only use this in debugging, it might be nice to have a production switch as well.

### PR DESCRIPTION
**Pull request by Delgan**
In the continuity of what has been discussed here: https://github.com/Qix-/better-exceptions/issues/38#issuecomment-329080260
This merges the automatic hook from [`better_exceptions_hook`](https://github.com/paradoxxxzero/better-exceptions-hook) directly to the `better_exceptions` package.

By default, the automatic hook is not enabled. After installing `better_exceptions`, the user must create the `BETTER_EXCEPTIONS` environment variable. Before each execution of a Python script, one checks whether the environment variable exists, and if so then `better_exceptions` is automatically activated without the need of an import.
Contrary to what I thought, it is not possible to automatically set the environment variable at the time of the package installation. User have to do it manually, but it's just a simple extra command.
The environment variable can be easily deactivated which allows to fix #24.
This also allowed to revert the ugly modifications I had made with #41.

Concerning the method used to install the automatic hook, I did not use that of `better_exceptions_hook` (`get_python_lib()` + `data_files`) because it did not work on my computer. Instead, I copied [the method used by pytest](https://github.com/pytest-dev/pytest-cov/blob/cde7c378b6a1971957759f42ac91e2860b41cf89/setup.py) which I suppose guarantees to work very well. I tested it under Windows, Linux and with virtual environment without encountering any problem.

If this new way to use better_exceptions without import suits you, it will of course be necessary to think about updating the README before the next release. It may also be interesting to give some troubleshooting indications if the automatic hook does not work. For example, I had to uninstall `python3-apport` to avoid a conflict because it replaced `sys.excepthook` too.

### CODE REVIEW

**Comment by Qix-** [comment]
I really like this approach. In the spirit of keeping `better_exceptions` completely hands-off from the code, this is what I'd expect from the functionality.

Can you update the README? When you feel it is ready, we'll push this as a major version change.

**Comment by Delgan** [comment]
@Qix- I have updated the README to describe the new environment variable.

I also added a "troubleshooting" section listing possible causes of errors, but maybe it's a little too long.

**Comment by Qix-** [comment]
Awesome - feel free to merge. Thanks so much for the work on this - this is exactly how I envisioned this module working long-term.

**Comment by Delgan** [comment]
@Qix- Thanks. I merged it, then. 😃

**Pull request merged**
