### PR TITLE
get_traceback_information: support frames

### PR DESCRIPTION
**Pull request by blueyed**
I am experimenting with using it from pdbpp, where only the frame is available there.

### CODE REVIEW

**Comment by blueyed** [comment]
I am probably not using it for frames, so feel free to close it - but it might be good to support frames (via an extra interface maybe) still.

**Comment by Qix-** [comment]
Could you explain a bit what this is doing?

**Comment by blueyed** [comment]
I wanted to use better-exceptions for tracebacks in pdbpp / pdb (the `w` command), but there only frames are available.
Therefore I wanted to use this to annotate those frames.
But it turns out to be very noisy, and I will not use it for this.

**Comment by Qix-** [comment]
I think that's a bit out of scope. Perhaps if it can be done in an elegant way we could re-introduce the idea. Thanks for the work put in though!

**Pull request closed without merging**
