### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by paradoxxxzero**
python 3 is out for almost 10 years, please don't release python 2 only libraries.

### CODE REVIEW

**Comment by povilasb** [comment]
+1

**Comment by P0P3YE** [comment]
So sad. I'm a Python 3 user but this looks awesome!

**Comment by paradoxxxzero** [comment]
Yeah but optimizing a list of around 10-100 elements with an iterator is not a relevant optimization

**Comment by acz13** [comment]
+1 merge plz

**Comment by Qix-** [comment]
Holy shit I posted this before I went to sleep expecting nothing and woke up to 130 stars and python 3 support lol.

Let me test really quick. Thanks for the quick PR.

**Pull request merged**
