### PR TITLE
format_value: catch BaseException

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/Qix-/better-exceptions/issues/85#issuecomment-489930136

### CODE REVIEW

**Comment by blueyed** [comment]
OTOH this would also swallow `KeyboardInterrupt` then.. which might be problematic if there's some infinite loop in multiple repr's - not sure if this is good.

**Comment by Qix-** [comment]
> OTOH this would also swallow `KeyboardInterrupt` then.. which might be problematic if there's some infinite loop in multiple repr's - not sure if this is good.

This is indeed problematic. Wouldn't it be okay to check if it's a `KeyboardInterrupt` exception?

**Comment by blueyed** [comment]
Ok, we could change it to raise KeyboardInterrupt still - is that what you mean?

**Comment by Qix-** [comment]
Yeah, I think something like this should work:


```python
# ....
except KeyboardInterrupt:
    raise
```

**Comment by blueyed** [comment]
Cool, amended.

**Comment by Qix-** [comment]
Yeah I think this looks okay. @Delgan any objections?

**Comment by Delgan** [comment]
@Qix- Yeah, this looks fine. :)

The standard library [doesn't even bother with `KeyboardInterupt`](https://github.com/python/cpython/blob/b35acc5b3a0148c5fd4462968b310fb436726d5a/Lib/traceback.py#L153-L157), but do catch `BaseException`, so this is a welcome improvement.

**Comment by Qix-** [comment]
Great :)

**Review by Delgan — COMMENTED** [review]
LGTM.

(Cleaning up my "Review requests" :) )

**Pull request merged**
