### PR TITLE
Update Django integration docs

### PR DESCRIPTION
**Pull request by sumanthratna**

### CODE REVIEW

**Comment by sumanthratna** [comment]
friendly bump @Qix-—don't want any other users to be confused about how to use the Django middleware correctly :)

**Comment by Qix-** [comment]
Thanks for the bump. :) Give me a few days to release this, if that's okay. I'm going to be distracted until next week 😅 

I appreciate all of the improvements by the way :)

**Comment by sumanthratna** [comment]
whoops forgot about this! @Qix- iirc, there hasn't been a release since this was merged

**Comment by Qix-** [comment]
Yeah it slipped away from me and Github still hasn't implemented a "remind me later" feature. I really should get around to implementing @RemindMe...

**Comment by Qix-** [comment]
Alright @sumanthratna should be published as `0.3.3`, let me know if not.

**Pull request merged**
