### PR TITLE
Add Django middleware

### LINKED ISSUE #108: Include Django middleware in better-exceptions
# Rationale
this would remove a lot of redundant code across Django projects

# Proposed API

```python
# better_exceptions/integrations/django.py (this repo)

from sys import exc_info
from better_exceptions import excepthook


class BetterExceptionsMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        return self.get_response(request)

    def process_exception(self, _, exception):
        _, _, traceback = exc_info()
        excepthook(exception.__class__, exception, traceback)
```
```python
# settings.py (user's Django project)

# ...
INSTALLED_APPS = [
    # ...
    "better_exceptions",
]
# ...
MIDDLEWARE = [
    # ...
    "better_exceptions.integrations.django.BetterExceptionsMiddleware",
]
# ...
```
This should be really easy to implement but I want to make sure you're (@Qix-) okay with maintaining this code.

### PR DESCRIPTION
**Pull request by sumanthratna**
closes #108 

WIP because unit test isn't ready

### CODE REVIEW

**Comment by Qix-** [comment]
Yeah this is a much better solution than the readme approach. Thanks for doing this :)

**Comment by Qix-** [comment]
Yeah looks good, thank you 👍

**Comment by sumanthratna** [comment]
@Qix- alright, this was a simple PR so I think this feature is ready to go!

**Comment by sumanthratna** [comment]
oh wow you just merged it :) thanks!

**Comment by Qix-** [comment]
Published as 0.3.0, thanks again!

**Pull request merged**
